### PR TITLE
use prefect task name as remote function name

### LINKED ISSUE #86: Propagating prefect task names to prefect tasks instead of it showing up as _run_prefect_task
# Expectation / Proposal
Propagate the prefect task name (whether function or manual name override in the task decorator) to the ray task.

# Traceback / Example
Screen Shot 2023-05-18 at 12 43 20 PM

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-ray/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by j-tr**
Closes #86

### Example

```
from prefect import flow, task
from prefect_ray import RayTaskRunner
from time import sleep

@task(
    name="Worker Task Name",
)
def worker_function():
    sleep(100)


@flow(task_runner=RayTaskRunner)
def main(
):
    worker_function.submit()

if __name__ == "__main__":
    main()
```

image

### Checklist

- [X] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-ray/issues/new/choose) first.
- [X] Includes tests or only affects documentation.
- [X] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [X] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-ray/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by azmyrajab** [comment]
this looks good to me - thanks a lot
Can we go ahead and merge this?

**Comment by azmyrajab** [comment]
@PrefectHQ/open-source, sorry to chase, wondering if someone can do a quick review to unblock this? Code looks good and the feature is very nice to have

**Comment by j-tr** [comment]
@desertaxle it would be great to receive some feedback on this :pray:

**Comment by desertaxle** [comment]
Tests are failing due to a new version of `pytest-asyncio`. I'll submit a PR to unblock CI.

**Pull request merged**
